<?php

/**
 * @file
 * Contains spacebase_projects.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Drupal\Component\Render\PlainTextOutput;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_help().
 */
function spacebase_projects_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spacebase_projects module.
    case 'help.page.spacebase_projects':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Project functionality for Spacebase') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter()
 */
function spacebase_projects_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'group_project_group_add_form') {
    $form['actions']['submit']['#value'] = t('Create Project');
  }
}


/**
 * Implements hook_mail_edit_keys().
 * Make it available to mail_edit to edit the template
 */
function spacebase_projects_mail_edit_templates() {
  return [
    'spacebase_projects.emails' => [
      'new_content_projects_org' => t('Org admins notice: Project created in Org.'),
      'new_content_projects' => t('Site admins notice: Project created.'),
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function spacebase_projects_mail($key, &$message, $params) {
  $token_service = \Drupal::token();
  $language_manager = \Drupal::languageManager();
  $langcode = $message['langcode'];
  $variables = ['user' => $params['account'], 'group' => $params['group']];

  $language = $language_manager->getLanguage($params['account']->getPreferredLangcode());
  $original_language = $language_manager->getConfigOverrideLanguage();
  $language_manager->setConfigOverrideLanguage($language);
  $mail_config = \Drupal::config('spacebase_projects.mail');

  $token_options = ['langcode' => $langcode, 'clear' => TRUE];
  $message['subject'] .= PlainTextOutput::renderFromHtml($token_service->replace($mail_config->get($key . '.subject'), $variables, $token_options));
  $message['body'][] = $token_service->replace($mail_config->get($key . '.body'), $variables, $token_options);

  $language_manager->setConfigOverrideLanguage($original_language);
}

function spacebase_projects_theme($existing, $type, $theme, $path) {
  return [
    'projects_pending_members_form' => [
      'render element' => 'form',
    ],
  ];
}

