<?php

/**
 * @file
 * Contains spacebase_projects.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;


/**
 * Implements hook_help().
 */
function spacebase_projects_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spacebase_projects module.
    case 'help.page.spacebase_projects':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Project functionality for Spacebase') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_node_insert().
 *
 * When new content is created, queue the node in order to email
 * the appropriate Admins (Organization or Site) on next cron.
 *
 */

function spacebase_projects_node_insert(NodeInterface $node) {

  if ($node->getType() == 'sb_project') {
    $module = 'spacebase_projects';
    $key = 'new_content_projects';
    spacebase_core_queue_content_notifications($module, $key, $node);
  }
}



/**
 * Implements hook_mail_edit_keys().
 * Make it available to mail_edit to edit the template
 */
function spacebase_projects_mail_edit_templates() {
  return [
    'spacebase_projects.emails' => [
      'new_content_projects_org' => t('Org admins notice: Project created in Org.'),
      'new_content_projects' => t('Site admins notice: Project created.'),
    ],
  ];
}

