<?php

/**
 * @file
 * Contains spacebase_videos.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function spacebase_videos_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spacebase_videos module.
    case 'help.page.spacebase_videos':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Video functionality for Spacebase') . '</p>';
      return $output;

    default:
  }
}
