<?php

/**
 * @file
 * Contains spacebase_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;


/**
 * Implements hook_help().
 */
function spacebase_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spacebase_core module.
    case 'help.page.spacebase_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Core custom functionality for spacebase website') . '</p>';
      return $output;

    default:
  }
}


/** Implements hook_preprocess_group() on behalf of spacebase_core.module.
 *
 * Prepare theme variables to show links/buttons to join, leave, or create
 * content for groups, or edit groups. A .show boolean and .url
 * Leaves developing link text and classes to theme/twig.
 * Based on both permissions and membership status (can't join a group
 * you already joined) set variables and make url's available to theme.
 */
function spacebase_preprocess_group(&$variables) {
  // I believe this will follow the same cache rules as
  // groups, if I don't change the cache rules here.
  // @ToDo: test

  $group = $variables['group'];
  $account = \Drupal::currentUser(); //or $variables['user']; ?
  // Note: if users can administer a group, all permissions are true.

  /** Thoughts on code duplication:
   
   * The first version of this worked mlore like the group module's operations
   * link code, which unfortunately is written in a way hard to reuse.
   * I think the new way is simpler, and should be the last step for 
   * SpaceBase ... so easier for themers and less extensible.
      $variables['group_leave']['show'] = true;
      $variables['group_leave']['url'] = 
        new Url('entity.group.leave', ['group' => $group->id()]);
       
   * Originally based on:
   * modules/gnode/src/Plugin/GroupContentEnabler/GroupNode.php
   * src/Plugin/GroupContentEnabler/GroupMembership.php
   * It's likely that this might be turned into a function and moved from
   * this preprocess, but not sure yet. Groups module might benefit
   * from a more generalized approach that provides the links so that 
   * they can be grabbed by any function, rather than locked into the
   * operations links function.
   */  

  /** Edit Group, Add Resource can be done by non-member admins.
   * If not, move inside getMember($account)
   */
  // Edit the group overall
  // /group/x/edit
  if ($group->hasPermission('edit group', $account)) {
    /*
    $variables['group_edit']['show'] = true;
    $variables['group_edit']['url'] =
      $group->toUrl('edit-form'); // need any $url_options ?
     */
    $variables['group_links']['group_edit'] = '/group/' . $group->id() . '/edit';
  }
  if ($group->hasPermission('administer members', $account)) {
    // @ToDo: review cache implications
    $variables['group_links']['group_manage_members'] = '/group/' . $group->id() . '/members';
    // If they can administer members, do they have pending applicants?
    $name = 'group_members';
    $display_id = 'page_2';
    $result = views_get_view_result($name, $display_id, $group->id());
    if ( count($result) > 0 ) {
      $variables['group_links']['group_manage_applicants'] =  '/group/' . $group->id() . '/applicants';
    }
  }

  // Possible futur @ToDo: turn this array if add forums and so on,
  // *and* those are also just permissions based.
  // Links look like:
  // group/20/content/create/group_node%3Aresources
  $plugin_id = 'group_node:resources';
  $quick_id = 'resources';
  if ($group->hasPermission("create $plugin_id entity", $account)) {
    $route_params = ['group' => $group->id(), 'plugin_id' => $plugin_id];
    $url = new Url('entity.group_content.create_form', $route_params);
    $variables['group_links']['group_create_'. $quick_id] =
      $url->toString();
  }

  /* Leave and join depend on membership status AND permission */  
  if ($group->getMember($account)) {

    if ($group->hasPermission('leave group', $account)) {
      $url =new Url('entity.group.leave', ['group' => $group->id()]);
      $variables['group_links']['leave'] = $url->toString();
    }
  } elseif ($group->hasPermission('join group', $account)) {
    $url = new Url('entity.group.join', ['group' => $group->id()]);
    $variables['group_links']['join'] = $url->toString();
  }

  // get resource_type terms
  $vid = 'resource_type';
  $terms =
    \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
  foreach ($terms as $term) {
    $variables['resource_type'][] = $term->name;
  }
}

/**
 * Implements hook_form_alter() on behalf of spacebase_core.module.
 */
function spacebase_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    $form['actions']['submit']['#submit'][] = 'spacebase_core_user_registration_submit';
  }
  else if ($form['#id'] == 'views-exposed-form-sitewide-search-search') {
    $form['keywords']['#attributes']['placeholder'] = 'Search';
    $form['#action'] = '/search';
  }
  else if ($form_id == 'node_resources_form') {
    foreach ($form['field_tab']['widget']['#options'] as $tid => $value) {
      //kint($value); // This is an object, being replaced with
      // a string. @ToRefactor, possibly instead use:
      // function hook_options_list_alter
      $term =  \Drupal\taxonomy\Entity\Term::load($tid);
      if ($descrip = $term->getDescription()) {
        $form['field_tab']['widget']['#options'][$tid] =
          $value . " <span class='descrip'>$descrip</span>";
      }
    }
  }
}

function spacebase_core_user_registration_submit(&$form, FormStateInterface $form_state) {
  drupal_set_message("An email will be sent to you with instructions to verify your email address and complete the sign-up process.");
  $url = url::fromUserInput("/user/login");
  $form_state->setRedirectUrl($url);
}

function spacebase_core_theme($existing, $type, $theme, $path) {
  return [
    'sb_search_page' => [
      'variables' => [
        'keywords' => '',
        'fullpage' => '',
        'orgs' => '',
        'org_count' => '',
        'people' => '',
        'people_count' => '',
      ],
    ],
  ];
}
