<?php

/**
 * @file
 * Contains spacebase_search.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter()
 */
function spacebase_search_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-sitewide-search-search') {
    $form['keywords']['#attributes']['placeholder'] = 'Search';
    $path = \Drupal::service('path.current')->getPath();
    $form['#action'] = '/search';
    if (strpos($path, '/search/') === 0) {
      $form['#action'] = $path;
    }
    if ($path == '/search/organizations') {
      $form['sf'] = array(
        '#type' => 'checkboxes',
        '#options' => array('group_name' => 'Name', 'group_description' => 'Description'),
      );
    }
  }
}

/**
 * Implements hook_views_pre_view()
 */
function spacebase_search_views_pre_view(Drupal\views\ViewExecutable $view) {
  if ($view->id() == 'sitewide_search') {
    if (!empty($_GET['sf'])) {
      $filters = $view->display_handler->getOption('filters');
      if ($filters['search_api_fulltext']) {
        unset($filters['search_api_fulltext']['fields']);
        foreach ($_GET['sf'] as $key) {
          $filters['search_api_fulltext']['fields'][$key] = $key;
        }
        $view->display_handler->overrideOption('filters', $filters);
      }
    }
  }
}

/**
 * Implements hook_theme_registry_alter()
 */
function spacebase_search_theme_registry_alter(&$theme_registry) {
  $theme_registry['calendar_pager']['path'] = drupal_get_path('module', 'spacebase_search') . '/templates';
}

/**
 * Implements hook_preprocess_HOOK()
 */
function spacebase_search_preprocess_calendar_pager(&$vars) {
  if (!$vars['exclude']) {
    $path = array_values(array_filter(explode('/', \Drupal::service('path.current')->getPath())));
    foreach (spacebase_search_calendar_get_key_formats() as $key => $format) {
      if ($path[1] == $key) {
        $vars['items']['today'] = [
          'url' => Url::fromUserInput("/events/{$key}/" . date($format)),
        ];
        $vars['items']['modes'] = [
          'label' => ucfirst($key),
          'links' => spacebase_search_get_calendar_mode_links($path[2], $format),
        ];
        break;
      }
    }
  }
}

/**
 * Creates a set of mode links for a given view
 */
function spacebase_search_preprocess_calendar_day_overlap(&$vars) {
  spacebase_saerch_process_hour_labels($vars['rows']['items']);
}

/**
 * Creates a set of mode links for a given view
 */
function spacebase_search_preprocess_calendar_week_overlap(&$vars) {
  $arg = $vars['view']->args[0];
  $date = new DateTime('now', new DateTimeZone('Pacific/Auckland'));
  $date->setISODate(substr($arg, 0, 4), substr($arg, -2), 0);
  foreach ($vars['day_names'] as $key => $value) {
    $vars['day_names'][$key]['data'] = "{$date->format('D')} {$date->format('j')}";
    $date->add(new DateInterval('P1D'));
  }
  spacebase_saerch_process_hour_labels($vars['items']);
}

/**
 * Formats calendar hour columns
 */
function spacebase_saerch_process_hour_labels(&$items) {
  foreach ($items as $start => $item) {
    $hour = (string) $items[$start]['hour'];
    if ($hour > 11) {
      $items[$start]['ampm'] .= 'pm';
      if ($hour > 12) {
        $hour -= 12;
      }
    }
    else {
      $items[$start]['ampm'] .= 'am';
    }
    $items[$start]['hour'] = ltrim($hour, '0') . ':00';
  }
}

/**
 * Creates a set of mode links for a given view
 */
function spacebase_search_get_calendar_mode_links($arg, $format) {
  if (empty($arg)) {
    $arg = date('Ymd');
  }

  switch ($format) {
    case 'Y':
      if ($arg != date($format)) {
        $arg .= '0101';
      }
      else {
        $arg .= date('md');
      }
      $date = date_create_from_format ('Ymd', $arg);
      break;
    case 'Ym':
      if ($arg != date($format)) {
        $arg .= '01';
      }
      else {
        $arg .= date('d');
      }
    case 'Ymd':
      $date = date_create_from_format ('Ymd', $arg);
      break;

    case 'YW':
      $date = new DateTime();
      $date->setISODate(substr($arg, 0, 4), substr($arg, -2));
      break;
  }

  $links = [];
  foreach (spacebase_search_calendar_get_key_formats() as $key => $format) {
    $links[] = [
      'label' => ucfirst($key),
      'url' => Url::fromUserInput("/events/{$key}/{$date->format($format)}"),
    ];
  }
  return $links;
}

function spacebase_search_calendar_get_key_formats() {
  return [
    'day' => 'Ymd',
    'week' => 'YW',
    'month' => 'Ym',
    'Year' => 'Y',
  ];
}