definitions:
  contact__site_page:
    weight: -50
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
  standard__front_page:
    weight: -49
    menu_name: main
    parent: ''
    enabled: false
    expanded: false
  user__page:
    weight: -48
    menu_name: account
    parent: ''
    enabled: false
    expanded: false
  user__logout:
    weight: -47
    menu_name: account
    parent: ''
    expanded: false
    enabled: false
  node__add__project_aim_update:
    enabled: false
    menu_name: admin
    parent: admin_toolbar_tools.add_content
    expanded: false
    weight: 0
  node__add__project_aim:
    enabled: false
    menu_name: admin
    parent: admin_toolbar_tools.add_content
    weight: 0
    expanded: false
  node__add__project_update:
    enabled: false
    menu_name: admin
    parent: admin_toolbar_tools.add_content
    weight: 0
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
