module:
  address: 0
  admin_toolbar: 0
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_type_templates: 0
  breakpoint: 0
  calendar: 0
  calendar_datetime: 0
  captcha: 0
  cer: 0
  charts: 0
  charts_c3: 0
  ckeditor: 0
  color: 0
  colorbox: 0
  comment: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  core_views_facets: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  email_group_administrators: 0
  entity: 0
  entity_reference: 0
  entity_reference_revisions: 0
  facets: 0
  facets_summary: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  gnode: 0
  google_analytics: 0
  group: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  layout_discovery: 0
  leaflet: 0
  leaflet_markercluster: 0
  leaflet_more_maps: 0
  leaflet_views: 0
  link: 0
  mail_edit: 0
  mailgun: 0
  mailsystem: 0
  markup: 0
  media: 0
  menu_link_attributes: 0
  menu_ui: 0
  message: 0
  message_notify: 0
  metatag: 0
  metatag_facebook: 0
  metatag_google_plus: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  migrate: 0
  migrate_plus: 0
  migrate_process_extra: 0
  migrate_process_extra_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  password_policy: 0
  password_policy_character_types: 0
  password_policy_characters: 0
  password_policy_consecutive: 0
  password_policy_history: 0
  password_policy_length: 0
  password_policy_username: 0
  path: 0
  path_alias: 0
  private_message: 0
  publishcontent: 0
  rdf: 0
  responsive_image: 0
  rest: 0
  riddler: 0
  schema_article: 0
  schema_event: 0
  schema_metatag: 0
  schema_person: 0
  schema_video_object: 0
  schema_web_page: 0
  schema_web_site: 0
  search_api: 0
  search_api_db: 0
  search_api_db_defaults: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  simple_block: 0
  smart_trim: 0
  social_api: 0
  social_auth: 0
  social_auth_google: 0
  spacebase_blogs: 0
  spacebase_core: 0
  spacebase_events: 0
  spacebase_facebook: 0
  spacebase_news: 0
  spacebase_orgs: 0
  spacebase_projects: 0
  spacebase_resources: 0
  spacebase_search: 0
  spacebase_users: 0
  spacebase_videos: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  variationcache: 0
  video_embed_field: 0
  video_embed_media: 0
  views_block_filter_block: 0
  views_bulk_operations: 0
  views_field_view: 0
  views_templates: 0
  views_ui: 0
  ds: 1
  menu_link_content: 1
  pathauto: 1
  ds_extras: 2
  views: 10
  empty_page: 1000
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  spacebase: 0
  adminimal_theme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
