id: contributed_news_articles
label: 'Contributed News Articles'
ui_limit: ''
properties:
  block: 'views_block:user_content-block_2'
  use_block_title: false
  add_block_wrappers: false
  config:
    id: 'views_block:user_content-block_2'
    label: ''
    provider: views
    label_display: visible
    views_label: ''
    items_per_page: none
    context_mapping: {  }
type: block
type_label: 'Block field'
entities:
  user: user
