id: private_message_inbox_label
label: 'Private message inbox label'
ui_limit: ''
properties:
  content:
    value: "<h2>Private Message Inbox</h2>\r\n"
    format: basic_html
type: token
type_label: 'Token field'
entities:
  private_message_thread: private_message_thread
  private_message: private_message
  user: user
