id: private_message_inbox_link
label: 'Private message inbox link'
ui_limit: ''
properties:
  block: 'simple_block:private_messages_inbox_link'
  use_block_title: false
  add_block_wrappers: true
type: block
type_label: 'Block field'
entities:
  private_message_thread: private_message_thread
  private_message: private_message
  user: user
