id: private_message_actions
label: 'Private message actions'
ui_limit: ''
properties:
  block: private_message_actions_block
  use_block_title: false
  add_block_wrappers: true
type: block
type_label: 'Block field'
entities:
  private_message_thread: private_message_thread
  private_message: private_message
  user: user
