id: user_groups
label: 'User Groups'
ui_limit: ''
properties:
  block: 'views_block:user_groups-block_1'
  use_block_title: false
  add_block_wrappers: true
  config:
    id: 'views_block:user_groups-block_1'
    label: ''
    provider: views
    label_display: visible
    views_label: ''
    items_per_page: none
    context_mapping: {  }
type: block
type_label: 'Block field'
entities:
  user: user
