unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: true
element_name: recovery-question
time_limit: 5
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  contact_message_feedback_form: true
  contact_message_personal_form: true
  node_article_form: true
  node_blog_post_form: true
  node_event_form: true
  node_group_forum_topic_form: true
  node_page_form: true
  node_partner_form: true
  node_project_aim_form: true
  node_project_aim_update_form: true
  node_project_update_form: true
  node_resources_form: true
  node_sb_news_article_form: true
  node_sb_video_form: true
  node_slide_form: true
  comment_comment_form: true
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
advanced_validation: true
