id: default
label: Default
password_reset: 0
langcode: en
policy_constraints:
  -
    id: character_types
    character_types: 3
  -
    id: consecutive
    max_consecutive_characters: 3
  -
    id: password_length
    character_length: 7
    character_operation: minimum
  -
    id: password_username
    disallow_username: true
roles:
  authenticated: authenticated
