enable_notifications: true
notify_by_default: false
notify_when_using: 'no'
number_of_seconds_considered_away: 120
hide_form_filter_tips: false
hide_recipient_field_when_prefilled: true
_core:
  default_config_hash: MbeU9ZYX8x1qoHsBz3PJOy-PoR7HkHwzOKY0sbgmGdo
inbox_label: 'Private Messages for me'
number_of_threads: 12
inbox_page_label: 'Private Message Inbox'
create_message_label: 'Create Private Message'
save_message_label: 'Send message'
autofocus_enable: true
