new_content_blogs_org:
  subject: 'New content: blog in ''[group:title]'' at [site:name]'
  body: "[user:display-name],\r\n\r\nA new blog was created for [group:title] at [site:name]:\r\n[node:title]"
new_content_blogs:
  subject: 'New content: blog at [site:name]'
  body: "[user:display-name],\r\n\r\nA new blog was created at [site:name]:\r\n\r\n[node:title]"
