cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://space-base.lndo.site/themes/custom/spacebase/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  spacebase: 8000
navbar_position: fixed-top
logo:
  path: themes/custom/spacebase/logo.png
  url: ''
  use_default: false
navbar_inverse: 1
region_wells:
  navigation: ''
  navdropdown: ''
  navigation_collapsible: ''
  header: ''
  branding: ''
  topbar: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer_top_1: ''
  footer_top_2: ''
  footer_top_3: ''
  footer_top_4: ''
  footer: ''
  groupmgt: ''
modal_enabled: 0
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
button_iconize: 0
table: ''
