new_content_news_org:
  subject: 'New content added: news in ''[group:title]'' at [site:name]'
  body: "[user:display-name],\r\n\r\nA news article was created for [group:title] at [site:name]:\r\n[node:title]"
new_content_news:
  subject: 'New content: news at [site:name]'
  body: "[user:display-name],\r\n\r\nA news article was created at [site:name]:\r\n\r\n[node:title]"
